'use strict';

const DRIVER_CLIENT_LIVE = 'ClientLive';
const DRIVER_CLIENT_LOCAL = 'ClientLocal';
const DRIVER_SENSOR = 'Sensor';
const DRIVER_SWITCH = 'Switch';

const DRIVER_CLIENTS = [
    DRIVER_CLIENT_LIVE,
    DRIVER_CLIENT_LOCAL
];

module.exports = {
    DRIVER_CLIENT_LIVE: DRIVER_CLIENT_LIVE,
    DRIVER_CLIENT_LOCAL: DRIVER_CLIENT_LOCAL,
    DRIVER_CLIENTS: DRIVER_CLIENTS
};

